### ISSUE TITLE
Crash if showed the alert in View Did Load

### ISSUE THREAD

**Issue by hamdshah** [thellimist/EZAlertController#5]
Created test-app and put the alert in "viewDidLoad"

![screen shot 2015-11-20 at 5 34 16 pm](https://cloud.githubusercontent.com/assets/1726321/11296428/08d94fdc-8fad-11e5-863e-f3ad298e3b47.png)

**Comment by Esqarrouth** [comment]
What happens when you move it to viewdidappear?

When you put it in viewDidLoad, you are basically telling the app to create the view, on a window that does not exist yet. Still I can fix this so it doesn't crash, but it won't show up either. Maybe I can make a counter and check when the view loads and show it accordingly

**Comment by hamdshah** [comment]
Yes exactly that's the issue.
It works in the "viewDidAppear".

**Comment by thellimist** [comment]
Fixed https://github.com/thellimist/EZAlertController/commit/7ef7f53d2ec92347a727f945b67677fea20cfd51
